id: P006679
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:15:29.926189
source_metadata:
  id: bdr:W5JW9
  title: མི
  author: ''
  volumes:
    1048e3dbaf254da6af2138bab7a49133:
      image_group_id: I1KG15563
      title: ''
      volume_number: 1
      total_pages: 56
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
